baseURL: /
title: "Slated, a New Theme"
defaultContentLanguage: en
languages:
  en:
    lang: en
    languageName: English
    weight: 1
MetaDataFormat: "yaml"
theme: "slated"
taxonomies:
  category: categories
  tag: tags
